runtime: nodejs20
env: standard

handlers:
# Serve all static files with url routing
- url: /(.*\..+)$
  static_files: dist/\1
  upload: dist/(.*\..+)$

# Catch all handler to index.html (for client-side routing)
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
